# Numpy Part-1

In [2]:
import numpy as np

### 1. Numpy 배열(N-Dimensional Array) 

In [2]:
a = np.array([1,3,4,7], float)
a

array([1., 3., 4., 7.])

In [3]:
a.dtype, a.shape, a.ndim, a.size

(dtype('float64'), (4,), 1, 4)

In [4]:
# Vector(1차원)
a = np.array([1,3,4,7], float)

In [6]:
#Matrix(2차원)
b = np.array([[1,2,4],[4,3,9],[3,7,8]])
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [9]:
b.dtype, b.shape, b.ndim, b.size

(dtype('int32'), (3, 3), 2, 9)

In [10]:
# Tensor(3차원)
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3, 4), 3, 24)

In [20]:
# d.type
np.array([1,2,3,4], dtype=np.uint8)

array([1, 2, 3, 4], dtype=uint8)

In [14]:
# reshape
c.size

24

In [15]:
c.reshape(4,6)    # size가 같으면 reshpae 가능

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
c.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [17]:
a.reshape(-1,4)

array([[1., 3., 4., 7.]])

In [19]:
# shape는 튜플
b.reshape(-1)

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

In [20]:
b.flatten()

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

### 2. Indexing and Slicing

In [21]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a[1][1]     #리스트 
a[1,1]      #NUmpy
a[-1,-2]

5

In [25]:
a[1, :2]

array([4, 5])

In [26]:
a[:,1:]

array([[2, 3],
       [5, 6]])

In [28]:
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [30]:
b[:2, 1:]

array([[2, 4],
       [3, 9]])

In [34]:
b[1:,:2]

array([[4, 3],
       [3, 7]])

In [35]:
b[:2,::2]

array([[1, 4],
       [4, 9]])

### 3. 배열 생성 

In [36]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [37]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [38]:
np.arange(1,4.1,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [39]:
l = np.arange(1,4.1,0.5).tolist()
l

[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]

In [41]:
np.arange(-2, 2.01, 0.02).size

201

In [42]:
#linear space
np.linspace(-2, 2, 201).size

201

- ones, zeros, empty

In [3]:
np.ones(shape=(10,), dtype=np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [4]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.zeros((4))

array([0., 0., 0., 0.])

In [6]:
np.empty(4)

array([0., 0., 0., 0.])

- 대각선: identity, eye

In [8]:
# 정방형(n x n)
np.identity(3, dtype=np.int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [10]:
# 직사각형 모양(N x M)
np.eye(N=3, M=5, dtype=np.int16)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int16)

In [13]:
np.eye(3, 5, k=1, dtype=np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

- 데이터 분포에 따른 random sampling

In [14]:
np.random.seed(2021)

In [16]:
np.random.random(4)

array([0.0968944 , 0.05857129, 0.96239599, 0.61655744])

In [17]:
np.random.normal(10, 4, 4)

array([10.49682738,  6.64818616, 11.63606282, 10.41100487])

In [18]:
# 표준 정규 분포
np.random.randn(4)      # np.random.normal(0, 1, 4)

array([-1.90772239,  1.1002243 , -1.40232506, -0.22508127])

In [19]:
# 균등 분포
np.random.uniform(3, 4, 4)

array([3.56930512, 3.19509597, 3.58370402, 3.47631347])