# Numpy - Part2

In [1]:
import numpy as np

### 4. Operation

In [3]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
a.sum()

78

In [5]:
a.sum(axis=0)

array([15, 18, 21, 24])

In [6]:
a.sum(axis=1)

array([10, 26, 42])

In [7]:
np.sum(a[0])

10

- sorting

In [8]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
np.sort(b)      # axis=1, ascending order

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [10]:
b.sort()
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [11]:
np.sort(b, axis=0)

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [12]:
# 내림차순일 경우에는 아래와 같은 방법으로

c = np.array([42, 38, 12, 25])
np.sort(c)[::-1]

array([42, 38, 25, 12])

In [13]:
np.argsort(c)

array([2, 3, 1, 0], dtype=int64)

In [14]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

In [16]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

- Mathematical functions

In [17]:
def sigmoid(x):     # 두가지 값을 내야하는 경우 유용
    return 1. / (1 + np.exp(-x))

In [18]:
xs = np.array([-10,0,10])
sigmoid(xs)


array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose (전치 행렬)

In [19]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [20]:
b.T

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concentenate, vstack, hstack

In [21]:
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

In [22]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [23]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

- Array operation

In [25]:
a + a

array([[2, 4],
       [6, 8]])

In [26]:
a - a

array([[0, 0],
       [0, 0]])

In [27]:
a * a

array([[ 1,  4],
       [ 9, 16]])

- braodcasting

In [28]:
a + 3

array([[4, 5],
       [6, 7]])

- dot product

In [29]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)

In [30]:
np.dot(a, b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [32]:
a.dot(b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

### 5. Comparison

- All & Any

In [34]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [35]:
np.any(a>5), np.all(a>5)

(True, False)

- Logical operation

In [37]:
b = np.logical_and(a>3, a<7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [38]:
np.logical_or(a<3, a>7)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [40]:
np.argmax(a), np.argmin(a)

(9, 0)

### 6. Boolean & Fancy index

- Boolean

In [45]:
a[a>5]

array([6, 7, 8, 9])

In [42]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [41]:
a[b]

array([4, 5, 6])

In [44]:
a[np.logical_or(a<3, a>7)]

array([0, 1, 2, 8, 9])

- Fancy index

In [46]:
a[[3,5,7]]

array([3, 5, 7])

In [47]:
a[[3,5,7,3]]

array([3, 5, 7, 3])

### 7. 기술 통계

In [49]:
a = np.random.randn(10)
a

array([-0.1650969 , -1.05992713,  1.29666445, -1.07512477, -0.19617932,
        2.06344246,  0.45748699,  1.79956725,  0.20869538, -0.60831014])

In [53]:
#평균 mean

a.mean(), np.mean(a)

(0.27212182773433297, 0.27212182773433297)

In [52]:
# 표준편차 standard

a.std(), np.std(a)

(1.0679440207241742, 1.0679440207241742)

In [54]:
a.max(), a.min()

(2.0634424567436027, -1.0751247667814983)

In [58]:
# 4분위수

np.percentile(a, 100), np.percentile(a, 0)


(2.0634424567436027, -1.0751247667814983)

In [57]:
np.percentile(a, 25), np.percentile(a, 75)

(-0.5052774344796866, 1.0868700859970026)

In [59]:
np.percentile(a, 50), np.median(a)

(0.021799242435634414, 0.021799242435634428)