In [2]:
import numpy as np

### Q1

In [3]:
a = np.array([[10,20,30,40], [50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### Q2

In [4]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [5]:
m[1, 2]

7

In [6]:
m[2,-1]

14

In [7]:
m[1, 1:3]

array([6, 7])

In [8]:
m[1:3, 2]

array([ 7, 12])

In [9]:
m[:2, 3:5]

array([[3, 4],
       [8, 9]])

### Q3

In [10]:
f = np.array(m).flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
a = f[f%3==0]
a

array([ 0,  3,  6,  9, 12])

In [12]:
b = f[f%4==1]
b

array([ 1,  5,  9, 13])

In [13]:
a[a%4==1]

array([9])

### Q4

In [14]:
a = np.identity(5, dtype=np.int16)

b = np.eye(N=4, M=5, dtype=np.int8)
b1 = np.vstack([np.zeros((1,5)), b])

c = np.eye(N=5, M=4, dtype=np.int8)
c1 = np.hstack([np.zeros((5, 1)), c])


In [15]:
(b1*3)+(a*2)+c1

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

### Q5

In [16]:
a = np.random.uniform(0,10,(5,6))
a

array([[0.88850892, 3.15871265, 8.00469402, 5.58984632, 5.29117809,
        2.36159726],
       [1.24160664, 0.06587152, 7.96475997, 1.51336851, 0.21074069,
        2.26649648],
       [6.50016028, 1.32806665, 8.12218743, 9.68191429, 0.95818547,
        3.9180281 ],
       [4.16745211, 7.07437179, 7.86670533, 7.44792086, 7.81184634,
        6.60942942],
       [4.53019356, 8.37308822, 4.44406778, 0.7048595 , 2.16893242,
        3.33494444]])

In [17]:
a.max()

9.681914287285739

In [18]:
a.sum(axis=1)

array([25.29453726, 13.2628438 , 30.50854223, 40.97772585, 23.55608593])

In [19]:
a.max(axis=1)

array([8.00469402, 7.96475997, 9.68191429, 7.86670533, 8.37308822])

In [20]:
a.mean(axis=0)

array([3.4655843 , 4.00002217, 7.28048291, 4.9875819 , 3.2881766 ,
       3.69809914])

In [21]:
a.min(axis=0)

array([0.88850892, 0.06587152, 4.44406778, 0.7048595 , 0.21074069,
       2.26649648])

### Q6

In [22]:
x = np.array([[1,2,3,4], [46,99,100,71], [81,59,90,100]])
x

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [23]:
y = x.argsort(axis=1)[1]
x[:,y]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

### Q7

In [24]:
a = np.random.randint(1,6,100)
a.mean()

2.96

### Q8

In [28]:
x = np.random.normal(size=250)

In [26]:
i = 10000

for k in x:
    i += i*k*(1/100)
i

9165.174233580277