In [2]:
import numpy as np

### Q1

In [3]:
a = np.array([[10,20,30,40], [50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [28]:
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### Q2

In [5]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [30]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
m[1, 2]

7

In [7]:
m[2,-1]

14

In [31]:
m[1, 1:3], m[1:2, 1:3]      # 슬라이스 갯수에 따라 차원 결정

(array([6, 7]), array([[6, 7]]))

In [9]:
m[1:3, 2]

array([ 7, 12])

In [10]:
m[:2, 3:5]

array([[3, 4],
       [8, 9]])

### Q3

In [11]:
f = np.array(m).flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
f = m.flatten()

In [12]:
a = f[f%3==0]
a

array([ 0,  3,  6,  9, 12])

In [13]:
b = f[f%4==1]
b

array([ 1,  5,  9, 13])

In [34]:
f[np.logical_and(f%3==0, f%4==1)]

array([9])

In [14]:
a[a%4==1]

array([9])

### Q4

In [15]:
a = np.identity(5, dtype=np.int16)

b = np.eye(N=4, M=5, dtype=np.int8)
b1 = np.vstack([np.zeros((1,5)), b])

c = np.eye(N=5, M=4, dtype=np.int8)
c1 = np.hstack([np.zeros((5, 1)), c])


In [16]:
(b1*3)+(a*2)+c1

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [38]:
np.eye(5,5,-1,dtype=int)*3 + np.eye(5,5,0,int)*2 + np.eye(5,5,1,int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

### Q5

In [40]:
a = np.random.uniform(0,10,(5,6))
a

array([[6.05978279, 7.33369361, 1.38947157, 3.12673084, 9.97243281,
        1.28162375],
       [1.78993106, 7.52925429, 6.62160514, 7.84310132, 0.96894396,
        0.58571285],
       [9.6239599 , 6.16557444, 0.86629961, 5.61272363, 6.16524709,
        9.63843023],
       [5.74304294, 3.71160848, 4.52145244, 2.01850248, 5.69305118,
        1.95095974],
       [5.83704016, 4.76313474, 5.178144  , 8.23098634, 7.32225027,
        0.69056275]])

In [42]:
np.random.seed(2021)
m = np.random.uniform(0,1,30).reshape(5,6).round(4)

In [18]:
a.max()

9.665208723872402

In [19]:
a.sum(axis=1)

array([33.95494556, 15.79929217, 23.8518853 , 25.51908485, 35.46818968])

In [20]:
a.max(axis=1)

array([9.66520872, 5.01564014, 6.76277099, 8.06575268, 9.33921836])

In [21]:
a.mean(axis=0)

array([2.60161238, 5.21128942, 3.67416988, 6.2314012 , 4.41457442,
       4.7856322 ])

In [22]:
a.min(axis=0)

array([0.00979529, 0.70044009, 0.64684444, 0.37416779, 0.2165748 ,
       0.01670291])

### Q6

In [23]:
x = np.array([[1,2,3,4], [46,99,100,71], [81,59,90,100]])
x

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [24]:
y = x.argsort(axis=1)[1]
x[:,y]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [43]:
score = np.array([[1,2,3,4], [46,99,100,71], [81,59,90,100]])

In [44]:
indices = np.argsort(score[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [45]:
# 내림차순
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [48]:
score[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [49]:
#한줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### Q7

In [50]:
np.random.seed(2021)
a = np.random.randint(1,7,100)
a.mean()

3.7

In [ ]:
# dice array에서 고유값
np.unique(a)

In [51]:
# dice array에서 고유값 및 갯수
np.unique(a, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [52]:
unique, counts = np.unique(a, return_counts=True)
dict(zip(unique, counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

### Q8

In [26]:
x = np.random.normal(size=250)

In [27]:
i = 10000

for k in x:
    i += i*k*(1/100)
i

7982.858387046811

In [53]:
# 5개만 먼저 테스트

np.random.seed(2021)
rate = np.random.normal(0, 0.01, 5)
price = 10000
for i in range(5):
    price= price*(1+rate[i])
    print(price, end=' ')

10148.860905266953 10217.468308310064 10174.713172248092 10092.651992843166 10148.754606030743 

In [57]:

np.random.seed(2021)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_list = []

for i in range(250):
    price= price + np.round(price*rate[i])
    price_list.append(price)
price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [59]:
np.random.seed(2021)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price= price + np.round(price*rate[i])
    price_array[i] = price
price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])